version: '3'

networks:
    backend:
        driver: ${NETWORKS_DRIVER}

volumes:
    dbdata:
        driver: ${VOLUMES_DRIVER}

services:

    workspace:
        build: ./workspace
        container_name: ${CONTAINER_WORKSPACE_NAME}
        restart: unless-stopped
        tty: true
        depends_on: 
            - mysql
        volumes: 
            - ./src:/var/www/
            - ./workspace/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports: 
            - "${WORKSPACE_PORT}:9000"
        networks: 
            - backend

    nginx:
        build: ./nginx
        container_name: ${CONTAINER_NGINX_NAME}
        restart: unless-stopped
        tty: true
        depends_on: 
            - workspace
        volumes: 
            - ./src:/var/www/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        networks: 
            - backend

    mysql:
        build: ./mysql
        container_name: ${CONTAINER_MYSQL_NAME}
        restart: unless-stopped
        tty: true
        env_file:
            - ./mysql/.env
        volumes:
            -  ${DATA_HOST}:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/conf.d/docker.cnf:/etc/mysql/conf.d/docker.cnf
            - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - backend